default:
  image: silex/emacs:27.2-ci

variables:
  HOME: "$CI_JOB_STAGE/.Home"

stages:
  - build
  - test

package-refresh:
  stage: build
  script:
    - emacs --batch --eval "(package-refresh-contents)"
  artifacts:
    paths:
      - $HOME/.emacs.d

build:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - make test
  dependencies:
    - build


