default:
  image: silex/emacs:27.2-ci


stages:
  - build
  - test

build:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - make test
  dependencies:
    - build


