default:
  image: silex/emacs:27.2-ci


stages:
  - build
  - test

package-refresh:
  stage: build
  script:
    - emacs --batch --eval "(require 'package) (package-refresh-contents)"
  artifacts:
    paths:
      - ~/.emacs.d/

build:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - make test
  dependencies:
    - build


